### attach upload
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization:BearerToken eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQzOTIwNDI3LCJleHAiOjE3NDQyNjYwMjd9.TMnaRVEf7JBs-SpN-rJmSTW1rpL3y-6wgIOxO7ECanPjqMd5AFEZiEigWG1v4HnnYSonwNJuqGQ4cG6TxLTkTg

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="logo1.jpg"

< C:\Users\hojia\Pictures\logo1.jpg

### attach open
GET http://localhost:8080/api/v1/attach/open_general/203e93bd-f1f8-4d42-88d7-d881df138d89.jpg





