### Registration
POST http://localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Xojiakbar",
  "surname": "Bek",
  "username": "codeuz91@gmail.com",
  "password": "1234"
}

### Registration Verification
GET http://localhost:8080/api/v1/auth/registration/verification/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ1NjgyMDcwLCJleHAiOjE3NDYwMjc2NzB9.AWSvsmdY6uhIDqlsWt1iUjGZFektBMNWOIo397L9UC0LQ_dXqRw7WA3ykV1Cm2CkO51Rqq2fEIWGWbYhbXS39w

### Login
POST http://localhost:8080/api/v1/auth/registration/login
Content-Type: application/json

{
  "username": "codeuz91@gmail.com",
  "password": "1234"
}

### reset password
POST http://localhost:8080/api/v1/auth/registration/reset
Content-Type: application/json

{
  "username": "codeuz91@gmail.com"
}

### resent password confirm
POST http://localhost:8080/api/v1/auth/registration/reset-password/confirm
Content-Type: application/json

{
  "username": "hojiakbarandaqulov5@gmail.com",
  "confirmCode": "1234",
  "password": "123456"
}




