### profile update detail
PUT http://localhost:8080/api/v1/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ0OTEwMDk5LCJleHAiOjE3NDUyNTU2OTl9.neD3ryoixltBtTUTdd-R6GdgwnMr1b6W-wMR1vQ3yxhxVKAgPovlxBel1QAyB3PXcautgxHyUeRLM6j8j4bDmQ

{
  "name": "Xojiakbar"
}

###profile password update
PUT http://localhost:8080/api/v1/profile/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2RldXo5MUBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiNSIsImlhdCI6MTc0ODAwNjI3OSwiZXhwIjoxNzQ4MzUxODc5fQ.IaYgIEZuTsqxa9VkemsZWYFkllc98gzbe96n1yi54qmUiXzX8pvt1392DiSPqJnkVQeN7Tvnn2E-oxo3YBNErQ

{
  "currentPassword": "1234",
  "newPassword": "123"
}

### username updated
PUT http://localhost:8080/api/v1/profile/update/username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ1NjgyMDcwLCJleHAiOjE3NDYwMjc2NzB9.AWSvsmdY6uhIDqlsWt1iUjGZFektBMNWOIo397L9UC0LQ_dXqRw7WA3ykV1Cm2CkO51Rqq2fEIWGWbYhbXS39w

{
  "username": "codeuz91@gmail.com",
  "confirmCode": "1234"
}

### profile update confirm
POST http://localhost:8080/api/v1/profile/update/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ1NjgyMDcwLCJleHAiOjE3NDYwMjc2NzB9.AWSvsmdY6uhIDqlsWt1iUjGZFektBMNWOIo397L9UC0LQ_dXqRw7WA3ykV1Cm2CkO51Rqq2fEIWGWbYhbXS39w

{
  "code": "55200"
}

### Update Profile Photo
PUT http://localhost:8080/api/v1/profile/photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbmRhcXVsb3Z4b2ppYWtiYXJAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc0NzY0NzI2NCwiZXhwIjoxNzQ3OTkyODY0fQ.Ihw3Jnj8Z3N6EPt5jeVY29LWj6qrZmDLyM8pvfiIym7zPVYct0nG2BhvXDSVBiDCokxJlFOY8Bu-XoorqaB_xg

{
  "photoId": "4ce5dbf5-f67e-4469-9819-048e8c3041da.jpg"
}


