### profile update detail
PUT http://localhost:8080/api/v1/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ0OTEwMDk5LCJleHAiOjE3NDUyNTU2OTl9.neD3ryoixltBtTUTdd-R6GdgwnMr1b6W-wMR1vQ3yxhxVKAgPovlxBel1QAyB3PXcautgxHyUeRLM6j8j4bDmQ

{
  "name": "Xojiakbar"
}

###profile password update
PUT http://localhost:8080/api/v1/profile/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiI1IiwiaWF0IjoxNzQ4MjY5NTIxLCJleHAiOjE3NDg2MTUxMjF9.4R87v84M_OX6_jvAvTbXZFMUovC1q1Yl6lJ3dCIf5rRnciByYN1MkxyGGRV9IFIPBaOX8MURWq0IJf_9FlhCpg

{
  "currentPassword": "1234",
  "newPassword": "123"
}

### username updated
PUT http://localhost:8080/api/v1/profile/update/username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiI1IiwiaWF0IjoxNzQ4MDg2ODYzLCJleHAiOjE3NDg0MzI0NjN9.NRMyw4w_NkBKzvzufxvZHCx2F91_ix7NVnngMj265dDbdW7uIalPK1OnkoopTWArRQ2RDpqYDrUB6Stom5GlBg

{
  "username": "codeuz91@gmail.com"
}

### profile update confirm
POST http://localhost:8080/api/v1/profile/update/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2RldXo5MUBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiNSIsImlhdCI6MTc0ODA3NzI3MiwiZXhwIjoxNzQ4NDIyODcyfQ.GDsx-zaLHFS4oAKkUAhN0nl70u0f8j2TOiKZ7omVWNCq8fwgT2dRXPFcEOT4L2b3M3hNrec0DOYLqj7OCzKpOw

{
  "code": "68702"
}

### Update Profile Photo
PUT http://localhost:8080/api/v1/profile/photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbmRhcXVsb3Z4b2ppYWtiYXJAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc0NzY0NzI2NCwiZXhwIjoxNzQ3OTkyODY0fQ.Ihw3Jnj8Z3N6EPt5jeVY29LWj6qrZmDLyM8pvfiIym7zPVYct0nG2BhvXDSVBiDCokxJlFOY8Bu-XoorqaB_xg

{
  "photoId": "4ce5dbf5-f67e-4469-9819-048e8c3041da.jpg"
}


