### profile update detail
PUT http://localhost:8080/api/v1/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ0OTEwMDk5LCJleHAiOjE3NDUyNTU2OTl9.neD3ryoixltBtTUTdd-R6GdgwnMr1b6W-wMR1vQ3yxhxVKAgPovlxBel1QAyB3PXcautgxHyUeRLM6j8j4bDmQ

{
  "name": "Xojiakbar"
}

###profile password update
PUT http://localhost:8080/api/v1/profile/update/password
Content-Type: application/json

{
  "currentPassword": "",
  "newPassword": ""
}

### username updated
PUT http://localhost:8080/api/v1/profile/update/username
Content-Type: application/json
Accept-Language: RU
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJob2ppYWtiYXJhbmRhcXVsb3Y1QGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIxIiwiaWF0IjoxNzQ0OTkwODg1LCJleHAiOjE3NDUzMzY0ODV9.6jdmq3xAp8lUD22m0KtJvwUcZlB0PJguANl8m2fOdMQkFeu4kHJktKamJeLxD1AVFSafH9j4-b16ai8uuR10hQ

{
  "username": "codeuz91@gmail.com"
}
